# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

float_max <- function() {
    .Call('_ijtiff_float_max', PACKAGE = 'ijtiff')
}

dims_cpp <- function(lst) {
    .Call('_ijtiff_dims_cpp', PACKAGE = 'ijtiff', lst)
}

enlist_img_cpp <- function(arr4d) {
    .Call('_ijtiff_enlist_img_cpp', PACKAGE = 'ijtiff', arr4d)
}

