// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// PasteCollapse
String PasteCollapse(CharacterVector strings, std::string collapse);
RcppExport SEXP filesstrings_PasteCollapse(SEXP stringsSEXP, SEXP collapseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type strings(stringsSEXP);
    Rcpp::traits::input_parameter< std::string >::type collapse(collapseSEXP);
    rcpp_result_gen = Rcpp::wrap(PasteCollapse(strings, collapse));
    return rcpp_result_gen;
END_RCPP
}
// PasteListElems
CharacterVector PasteListElems(List string_list, std::string collapse);
RcppExport SEXP filesstrings_PasteListElems(SEXP string_listSEXP, SEXP collapseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type string_list(string_listSEXP);
    Rcpp::traits::input_parameter< std::string >::type collapse(collapseSEXP);
    rcpp_result_gen = Rcpp::wrap(PasteListElems(string_list, collapse));
    return rcpp_result_gen;
END_RCPP
}
// StrListRemoveEmpties
List StrListRemoveEmpties(List string_list);
RcppExport SEXP filesstrings_StrListRemoveEmpties(SEXP string_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type string_list(string_listSEXP);
    rcpp_result_gen = Rcpp::wrap(StrListRemoveEmpties(string_list));
    return rcpp_result_gen;
END_RCPP
}
// CharListElemsNthElem
CharacterVector CharListElemsNthElem(List string_list, int n);
RcppExport SEXP filesstrings_CharListElemsNthElem(SEXP string_listSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type string_list(string_listSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(CharListElemsNthElem(string_list, n));
    return rcpp_result_gen;
END_RCPP
}
// NumListElemsNthElem
NumericVector NumListElemsNthElem(List num_list, int n);
RcppExport SEXP filesstrings_NumListElemsNthElem(SEXP num_listSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type num_list(num_listSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(NumListElemsNthElem(num_list, n));
    return rcpp_result_gen;
END_RCPP
}
