# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IJDefault <- function(data) {
    .Call(`_autothresholdr_IJDefault`, data)
}

Huang <- function(data) {
    .Call(`_autothresholdr_Huang`, data)
}

Huang2 <- function(data) {
    .Call(`_autothresholdr_Huang2`, data)
}

Intermodes <- function(data) {
    .Call(`_autothresholdr_Intermodes`, data)
}

IsoData <- function(data) {
    .Call(`_autothresholdr_IsoData`, data)
}

Li <- function(data) {
    .Call(`_autothresholdr_Li`, data)
}

MaxEntropy <- function(data) {
    .Call(`_autothresholdr_MaxEntropy`, data)
}

Mean <- function(data) {
    .Call(`_autothresholdr_Mean`, data)
}

MinErrorI <- function(data) {
    .Call(`_autothresholdr_MinErrorI`, data)
}

Minimum <- function(data) {
    .Call(`_autothresholdr_Minimum`, data)
}

Moments <- function(data) {
    .Call(`_autothresholdr_Moments`, data)
}

Otsu <- function(data) {
    .Call(`_autothresholdr_Otsu`, data)
}

Percentile <- function(data) {
    .Call(`_autothresholdr_Percentile`, data)
}

RenyiEntropy <- function(data) {
    .Call(`_autothresholdr_RenyiEntropy`, data)
}

Shanbhag <- function(data) {
    .Call(`_autothresholdr_Shanbhag`, data)
}

Triangle <- function(data) {
    .Call(`_autothresholdr_Triangle`, data)
}

Yen <- function(data) {
    .Call(`_autothresholdr_Yen`, data)
}

sum_pillars <- function(arr3d) {
    .Call(`_autothresholdr_sum_pillars`, arr3d)
}

mean_pillars <- function(arr3d) {
    .Call(`_autothresholdr_mean_pillars`, arr3d)
}

var_pillars <- function(arr3d) {
    .Call(`_autothresholdr_var_pillars`, arr3d)
}

median_pillars <- function(arr3d) {
    .Call(`_autothresholdr_median_pillars`, arr3d)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_autothresholdr_RcppExport_registerCCallable', PACKAGE = 'autothresholdr')
})
