# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intmat_list_nrows <- function(intmat_list) {
    .Call(`_filesstrings_intmat_list_nrows`, intmat_list)
}

