# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PasteCollapse <- function(strings, collapse) {
    .Call('filesstrings_PasteCollapse', PACKAGE = 'filesstrings', strings, collapse)
}

#' @export
PasteListElems <- function(string_list, collapse = "") {
    .Call('filesstrings_PasteListElems', PACKAGE = 'filesstrings', string_list, collapse)
}

#' @export
StrListRemoveEmpties <- function(string_list) {
    .Call('filesstrings_StrListRemoveEmpties', PACKAGE = 'filesstrings', string_list)
}

#' @export
CharListElemsNthElem <- function(string_list, n) {
    .Call('filesstrings_CharListElemsNthElem', PACKAGE = 'filesstrings', string_list, n)
}

#' @export
NumListElemsNthElem <- function(num_list, n) {
    .Call('filesstrings_NumListElemsNthElem', PACKAGE = 'filesstrings', num_list, n)
}

IsPrefix <- function(pre, whole) {
    .Call('filesstrings_IsPrefix', PACKAGE = 'filesstrings', pre, whole)
}

InterleaveStrings <- function(strings1, strings2) {
    .Call('filesstrings_InterleaveStrings', PACKAGE = 'filesstrings', strings1, strings2)
}

CorrectInterleave0 <- function(orig, strings1, strings2) {
    .Call('filesstrings_CorrectInterleave0', PACKAGE = 'filesstrings', orig, strings1, strings2)
}

CorrectInterleave <- function(orig, strings1, strings2) {
    .Call('filesstrings_CorrectInterleave', PACKAGE = 'filesstrings', orig, strings1, strings2)
}

InterleaveStringList <- function(strings1, strings2) {
    .Call('filesstrings_InterleaveStringList', PACKAGE = 'filesstrings', strings1, strings2)
}

